### PR TITLE
~Fixed past sumbit listed in future~ Reverted, it only brings CS stuff

### PR DESCRIPTION
**Pull request by welcoMattic**
Ref https://github.com/jolicode/starfleet/issues/240

### CODE REVIEW

**Comment by lyrixx** [comment]
Can you check the tests ?

**Comment by welcoMattic** [comment]
After reconsidering the fix, it's not the right way to do. Submits must be in the right status all the times, it's during the fetch that we have to check if an accepted submit is in the future or not.

**Comment by lyrixx** [comment]
Nothing really change here, right?

**Comment by welcoMattic** [comment]
No, nothing, I choose to revert the fix (which is wrong)

**Pull request merged**
